### Задание 1

In [1]:
import numpy as np

In [2]:
a = np.array([[1, 6], [2, 8], [3, 11], [3, 10], [1, 7]])

In [3]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [6]:
mean_a = a.mean(axis=0)

In [7]:
mean_a

array([2. , 8.4])

### Задание 2

In [9]:
a_centered = a - mean_a

In [10]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание 3

In [11]:
a_centered_sp = a_centered[:, 0].dot(a_centered[:, 1])

In [12]:
a_centered_sp

8.0

In [17]:
cov_a_1 = a_centered_sp / (5 - 1) #число наблюдений N - число строк в матрице a

In [18]:
cov_a_1

2.0

### Задание 4

In [21]:
a_T = a.T

In [22]:
a_T

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [23]:
a_cov = np.cov(a_T)

In [24]:
a_cov

array([[1. , 2. ],
       [2. , 4.3]])

In [25]:
cov_a_2 = a_cov[0, 1]

In [26]:
cov_a_2

2.0

In [27]:
cov_a_1 == cov_a_2

True

In [29]:
cov_a_2 = np.cov(a_T)[0, 1] #короче вариант

In [30]:
cov_a_2

2.0